[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[rewrites]]
  from = "/"
  to = "/admin.html"
  status = 200
  domain = "admin.gemasagara.online"

[[rewrites]]
  from = "/"
  to = "/index.html"
  status = 200